#!/usr/bin/env python3
"""
Accuracy Calculator - Compare Algorithm Estimates vs Actual Quotes

Reads:
- estimated-quotes.csv (generated by run_algorithm.py)
- actual-quotes.csv (filled in by human after collecting real quotes)

Outputs:
- ACCURACY-REPORT.md (comprehensive analysis)
- accuracy-metrics.csv (raw metrics data)

This script is run by human AFTER collecting actual quotes.
"""

import csv
import os
import sys
from datetime import datetime
from typing import Dict, List, Tuple
import statistics


def load_estimates(path: str) -> Dict:
    """Load algorithm estimates by route_id"""
    estimates = {}
    with open(path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            route_id = row['route_id']
            estimates[route_id] = row
    return estimates


def load_actuals(path: str) -> Dict:
    """Load actual quotes by route_id"""
    actuals = {}
    with open(path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            route_id = row['route_id']
            actuals[route_id] = row
    return actuals


def calculate_error(estimated: float, actual: float) -> Dict:
    """
    Calculate various error metrics

    Returns:
        dict with absolute_error, percentage_error, within_20_pct
    """
    if actual == 0:
        return {
            'absolute_error': None,
            'percentage_error': None,
            'within_20_pct': None
        }

    absolute_error = abs(estimated - actual)
    percentage_error = (absolute_error / actual) * 100
    within_20_pct = percentage_error <= 20

    return {
        'absolute_error': round(absolute_error, 2),
        'percentage_error': round(percentage_error, 1),
        'within_20_pct': within_20_pct
    }


def analyze_accuracy(estimates: Dict, actuals: Dict) -> Dict:
    """
    Perform comprehensive accuracy analysis

    Returns:
        dict with all metrics and analysis
    """
    results = {
        'uber_errors': [],
        'lyft_errors': [],
        'recommendation_accuracy': [],
        'details': []
    }

    for route_id, estimate in estimates.items():
        actual = actuals.get(route_id)

        if not actual:
            continue

        # Skip if actual quotes not filled in
        if not actual.get('actual_uber') or not actual.get('actual_lyft'):
            continue

        try:
            # Parse values
            est_uber = float(estimate['uber_estimate'])
            est_lyft = float(estimate['lyft_estimate'])
            act_uber = float(actual['actual_uber'])
            act_lyft = float(actual['actual_lyft'])
            est_recommendation = estimate['recommendation']

            # Calculate errors
            uber_error = calculate_error(est_uber, act_uber)
            lyft_error = calculate_error(est_lyft, act_lyft)

            results['uber_errors'].append(uber_error)
            results['lyft_errors'].append(lyft_error)

            # Check if our recommendation was correct
            actual_best = 'lyft' if act_lyft < act_uber else 'uber'
            recommendation_correct = est_recommendation == actual_best
            results['recommendation_accuracy'].append(recommendation_correct)

            # Detailed results per route
            results['details'].append({
                'route_id': route_id,
                'city': estimate['city'],
                'distance_category': estimate['distance_category'],
                'est_uber': est_uber,
                'act_uber': act_uber,
                'uber_error_pct': uber_error['percentage_error'],
                'est_lyft': est_lyft,
                'act_lyft': act_lyft,
                'lyft_error_pct': lyft_error['percentage_error'],
                'est_recommendation': est_recommendation,
                'actual_best': actual_best,
                'recommendation_correct': recommendation_correct,
                'surge_active': actual.get('surge_active', 'unknown'),
            })

        except (ValueError, KeyError) as e:
            print(f"Skipping route {route_id}: {e}")
            continue

    return results


def calculate_summary_metrics(results: Dict) -> Dict:
    """Calculate summary statistics from analysis results"""
    uber_pct_errors = [e['percentage_error'] for e in results['uber_errors']
                       if e['percentage_error'] is not None]
    lyft_pct_errors = [e['percentage_error'] for e in results['lyft_errors']
                       if e['percentage_error'] is not None]

    uber_within_20 = sum(1 for e in results['uber_errors']
                         if e.get('within_20_pct'))
    lyft_within_20 = sum(1 for e in results['lyft_errors']
                         if e.get('within_20_pct'))

    total_routes = len(results['details'])
    correct_recommendations = sum(results['recommendation_accuracy'])

    metrics = {
        'total_routes_analyzed': total_routes,
        'uber': {
            'mean_error_pct': round(statistics.mean(uber_pct_errors), 1) if uber_pct_errors else None,
            'median_error_pct': round(statistics.median(uber_pct_errors), 1) if uber_pct_errors else None,
            'max_error_pct': round(max(uber_pct_errors), 1) if uber_pct_errors else None,
            'min_error_pct': round(min(uber_pct_errors), 1) if uber_pct_errors else None,
            'within_20_pct_count': uber_within_20,
            'within_20_pct_rate': round(100 * uber_within_20 / total_routes, 1) if total_routes else None,
        },
        'lyft': {
            'mean_error_pct': round(statistics.mean(lyft_pct_errors), 1) if lyft_pct_errors else None,
            'median_error_pct': round(statistics.median(lyft_pct_errors), 1) if lyft_pct_errors else None,
            'max_error_pct': round(max(lyft_pct_errors), 1) if lyft_pct_errors else None,
            'min_error_pct': round(min(lyft_pct_errors), 1) if lyft_pct_errors else None,
            'within_20_pct_count': lyft_within_20,
            'within_20_pct_rate': round(100 * lyft_within_20 / total_routes, 1) if total_routes else None,
        },
        'recommendation': {
            'correct_count': correct_recommendations,
            'accuracy_rate': round(100 * correct_recommendations / total_routes, 1) if total_routes else None,
        },
        'overall': {
            'combined_within_20_pct': round(100 * (uber_within_20 + lyft_within_20) / (2 * total_routes), 1) if total_routes else None,
        }
    }

    return metrics


def analyze_by_category(results: Dict) -> Dict:
    """Analyze accuracy by distance category and city"""
    by_distance = {}
    by_city = {}

    for detail in results['details']:
        # By distance category
        cat = detail['distance_category']
        if cat not in by_distance:
            by_distance[cat] = {'uber_errors': [], 'lyft_errors': [], 'correct': 0, 'total': 0}

        by_distance[cat]['uber_errors'].append(detail['uber_error_pct'])
        by_distance[cat]['lyft_errors'].append(detail['lyft_error_pct'])
        by_distance[cat]['correct'] += 1 if detail['recommendation_correct'] else 0
        by_distance[cat]['total'] += 1

        # By city
        city = detail['city']
        if city not in by_city:
            by_city[city] = {'uber_errors': [], 'lyft_errors': [], 'correct': 0, 'total': 0}

        by_city[city]['uber_errors'].append(detail['uber_error_pct'])
        by_city[city]['lyft_errors'].append(detail['lyft_error_pct'])
        by_city[city]['correct'] += 1 if detail['recommendation_correct'] else 0
        by_city[city]['total'] += 1

    # Calculate summaries
    distance_summary = {}
    for cat, data in by_distance.items():
        distance_summary[cat] = {
            'uber_mean_error': round(statistics.mean(data['uber_errors']), 1) if data['uber_errors'] else None,
            'lyft_mean_error': round(statistics.mean(data['lyft_errors']), 1) if data['lyft_errors'] else None,
            'recommendation_accuracy': round(100 * data['correct'] / data['total'], 1) if data['total'] else None,
            'total_routes': data['total'],
        }

    city_summary = {}
    for city, data in by_city.items():
        city_summary[city] = {
            'uber_mean_error': round(statistics.mean(data['uber_errors']), 1) if data['uber_errors'] else None,
            'lyft_mean_error': round(statistics.mean(data['lyft_errors']), 1) if data['lyft_errors'] else None,
            'recommendation_accuracy': round(100 * data['correct'] / data['total'], 1) if data['total'] else None,
            'total_routes': data['total'],
        }

    return {
        'by_distance': distance_summary,
        'by_city': city_summary,
    }


def generate_report(metrics: Dict, categories: Dict, results: Dict, output_path: str):
    """Generate comprehensive markdown report"""

    report = f"""# Accuracy Validation Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Routes Analyzed:** {metrics['total_routes_analyzed']}

---

## Executive Summary

| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| Uber within 20% | 85% | {metrics['uber']['within_20_pct_rate']}% | {'PASS' if metrics['uber']['within_20_pct_rate'] and metrics['uber']['within_20_pct_rate'] >= 85 else 'FAIL'} |
| Lyft within 20% | 85% | {metrics['lyft']['within_20_pct_rate']}% | {'PASS' if metrics['lyft']['within_20_pct_rate'] and metrics['lyft']['within_20_pct_rate'] >= 85 else 'FAIL'} |
| Recommendation Accuracy | 80% | {metrics['recommendation']['accuracy_rate']}% | {'PASS' if metrics['recommendation']['accuracy_rate'] and metrics['recommendation']['accuracy_rate'] >= 80 else 'FAIL'} |
| Overall Accuracy | 85% | {metrics['overall']['combined_within_20_pct']}% | {'PASS' if metrics['overall']['combined_within_20_pct'] and metrics['overall']['combined_within_20_pct'] >= 85 else 'FAIL'} |

---

## Detailed Metrics

### Uber Estimates

| Metric | Value |
|--------|-------|
| Mean Error | {metrics['uber']['mean_error_pct']}% |
| Median Error | {metrics['uber']['median_error_pct']}% |
| Min Error | {metrics['uber']['min_error_pct']}% |
| Max Error | {metrics['uber']['max_error_pct']}% |
| Within 20% | {metrics['uber']['within_20_pct_count']}/{metrics['total_routes_analyzed']} ({metrics['uber']['within_20_pct_rate']}%) |

### Lyft Estimates

| Metric | Value |
|--------|-------|
| Mean Error | {metrics['lyft']['mean_error_pct']}% |
| Median Error | {metrics['lyft']['median_error_pct']}% |
| Min Error | {metrics['lyft']['min_error_pct']}% |
| Max Error | {metrics['lyft']['max_error_pct']}% |
| Within 20% | {metrics['lyft']['within_20_pct_count']}/{metrics['total_routes_analyzed']} ({metrics['lyft']['within_20_pct_rate']}%) |

---

## Analysis by Distance Category

| Category | Uber Error | Lyft Error | Recommendation Accuracy | Routes |
|----------|------------|------------|-------------------------|--------|
"""

    for cat in ['short', 'medium', 'long']:
        if cat in categories['by_distance']:
            data = categories['by_distance'][cat]
            report += f"| {cat} | {data['uber_mean_error']}% | {data['lyft_mean_error']}% | {data['recommendation_accuracy']}% | {data['total_routes']} |\n"

    report += """
---

## Analysis by City

| City | Uber Error | Lyft Error | Recommendation Accuracy | Routes |
|------|------------|------------|-------------------------|--------|
"""

    for city in sorted(categories['by_city'].keys()):
        data = categories['by_city'][city]
        report += f"| {city} | {data['uber_mean_error']}% | {data['lyft_mean_error']}% | {data['recommendation_accuracy']}% | {data['total_routes']} |\n"

    report += """
---

## Route-Level Details

| Route | City | Distance | Est Uber | Act Uber | Error | Est Lyft | Act Lyft | Error | Rec OK? |
|-------|------|----------|----------|----------|-------|----------|----------|-------|---------|
"""

    for detail in sorted(results['details'], key=lambda x: int(x['route_id'])):
        rec_ok = 'YES' if detail['recommendation_correct'] else 'NO'
        report += f"| {detail['route_id']} | {detail['city']} | {detail['distance_category']} | ${detail['est_uber']:.2f} | ${detail['act_uber']:.2f} | {detail['uber_error_pct']}% | ${detail['est_lyft']:.2f} | ${detail['act_lyft']:.2f} | {detail['lyft_error_pct']}% | {rec_ok} |\n"

    report += """
---

## Recommendations for Improvement

"""

    # Identify problem areas
    if metrics['uber']['mean_error_pct'] and metrics['uber']['mean_error_pct'] > 20:
        report += "1. **Uber Estimates High Error**: Consider recalibrating Uber rate cards or surge prediction model.\n"

    if metrics['lyft']['mean_error_pct'] and metrics['lyft']['mean_error_pct'] > 20:
        report += "2. **Lyft Estimates High Error**: Consider recalibrating Lyft rate cards or surge prediction model.\n"

    # Check for city-specific issues
    for city, data in categories['by_city'].items():
        if data['uber_mean_error'] and data['uber_mean_error'] > 25:
            report += f"3. **{city} needs attention**: High error rates suggest rate cards may be outdated.\n"

    # Check distance-based patterns
    for cat, data in categories['by_distance'].items():
        if data['uber_mean_error'] and data['uber_mean_error'] > 25:
            report += f"4. **{cat.upper()} distance category**: Algorithm may need adjustment for {cat} routes.\n"

    report += """
---

## Next Steps

1. Review high-error routes and identify patterns
2. Update rate cards for cities with high error rates
3. Consider surge prediction model improvements
4. Re-run validation after adjustments
5. Target: 85%+ within 20% accuracy before launch

---

*Report generated by calculate_accuracy.py*
"""

    with open(output_path, 'w') as f:
        f.write(report)

    print(f"Report generated: {output_path}")


def save_metrics_csv(results: Dict, output_path: str):
    """Save detailed metrics to CSV for further analysis"""
    fieldnames = [
        'route_id', 'city', 'distance_category',
        'est_uber', 'act_uber', 'uber_error_pct',
        'est_lyft', 'act_lyft', 'lyft_error_pct',
        'est_recommendation', 'actual_best', 'recommendation_correct',
        'surge_active'
    ]

    with open(output_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results['details'])

    print(f"Metrics CSV saved: {output_path}")


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(os.path.dirname(script_dir), 'output')

    estimates_path = os.path.join(script_dir, 'estimated-quotes.csv')
    actuals_path = os.path.join(script_dir, 'actual-quotes.csv')  # Human fills from template
    report_path = os.path.join(output_dir, 'ACCURACY-REPORT.md')
    metrics_csv_path = os.path.join(script_dir, 'accuracy-metrics.csv')

    # Check for required files
    if not os.path.exists(estimates_path):
        print(f"ERROR: {estimates_path} not found!")
        print("Run run_algorithm.py first.")
        sys.exit(1)

    if not os.path.exists(actuals_path):
        print(f"ERROR: {actuals_path} not found!")
        print("")
        print("INSTRUCTIONS:")
        print("1. Copy actual-quotes-template.csv to actual-quotes.csv")
        print("2. Collect real Uber/Lyft quotes for each route")
        print("3. Fill in actual_uber and actual_lyft columns")
        print("4. Re-run this script")
        print("")
        print("See output/QUOTE-COLLECTION-GUIDE.md for detailed instructions.")
        sys.exit(1)

    # Load data
    print("Loading data...")
    estimates = load_estimates(estimates_path)
    actuals = load_actuals(actuals_path)

    # Analyze
    print("Analyzing accuracy...")
    results = analyze_accuracy(estimates, actuals)

    if not results['details']:
        print("ERROR: No valid comparison data found!")
        print("Make sure actual-quotes.csv has actual_uber and actual_lyft filled in.")
        sys.exit(1)

    # Calculate metrics
    metrics = calculate_summary_metrics(results)
    categories = analyze_by_category(results)

    # Generate outputs
    os.makedirs(output_dir, exist_ok=True)
    generate_report(metrics, categories, results, report_path)
    save_metrics_csv(results, metrics_csv_path)

    # Print summary
    print("\n" + "=" * 60)
    print("ACCURACY VALIDATION COMPLETE")
    print("=" * 60)
    print(f"\nOverall Accuracy: {metrics['overall']['combined_within_20_pct']}% within 20%")
    print(f"Target: 85%+")
    print(f"Status: {'PASS' if metrics['overall']['combined_within_20_pct'] and metrics['overall']['combined_within_20_pct'] >= 85 else 'NEEDS IMPROVEMENT'}")
    print(f"\nRecommendation Accuracy: {metrics['recommendation']['accuracy_rate']}%")
    print("\nFull report: " + report_path)


if __name__ == "__main__":
    main()
