"""AutoIterator Optimization Report PDF Template."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import Spacer, Paragraph, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle

from branded_pdf_engine import (
    register_template, BrandConfig, get_brand_styles,
    section_title, accent_line, bullet_list, branded_table
)

GOLD = HexColor(BrandConfig.GOLD)
DARK = HexColor(BrandConfig.DARK_BG)
LIGHT_TEXT = HexColor("#cccccc")


@register_template("optimization_report")
def render(data: dict, styles: dict):
    """
    Render weekly AutoIterator optimization report.

    Expected data keys:
        title: str
        period: str (e.g. "March 7-14, 2026")
        domains: list of dicts, each with:
            name: str
            stats: dict (total, kept, reverted, proposed, deployed)
            improvement_pct: float
            active_experiments: list of dicts
            recent_learnings: list of dicts
            best_variant: dict (text, score, hypothesis) or None
    """
    story = []

    # Title
    story.append(Paragraph(data.get("title", "Optimization Report"), styles["Title"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Period: {data.get('period', 'N/A')} | Generated by AutoIterator",
        styles["Subtitle"]
    ))
    story.append(accent_line())
    story.append(Spacer(1, 12))

    # Executive summary
    total_experiments = sum(d.get("stats", {}).get("total", 0) for d in data.get("domains", []))
    total_kept = sum(d.get("stats", {}).get("kept", 0) for d in data.get("domains", []))
    total_reverted = sum(d.get("stats", {}).get("reverted", 0) for d in data.get("domains", []))

    story.extend(section_title("Executive Summary", styles))
    summary_items = [
        f"<b>{total_experiments}</b> total experiments across {len(data.get('domains', []))} domains",
        f"<b>{total_kept}</b> improvements kept, <b>{total_reverted}</b> reverted",
    ]

    # Add per-domain improvement highlights
    for domain in data.get("domains", []):
        imp = domain.get("improvement_pct", 0)
        if imp > 0:
            summary_items.append(
                f"<b>{domain['name']}</b>: +{imp}% cumulative improvement"
            )

    story.extend(bullet_list(summary_items, styles))
    story.append(Spacer(1, 16))

    # Per-domain sections
    for domain in data.get("domains", []):
        story.extend(section_title(f"Domain: {domain['name'].replace('_', ' ').title()}", styles))

        # Stats table
        stats = domain.get("stats", {})
        stats_data = [
            ["Metric", "Value"],
            ["Total Experiments", str(stats.get("total", 0))],
            ["Kept (improved)", str(stats.get("kept", 0))],
            ["Reverted", str(stats.get("reverted", 0))],
            ["Pending Approval", str(stats.get("proposed", 0))],
            ["Currently Deployed", str(stats.get("deployed", 0))],
            ["Cumulative Improvement", f"+{domain.get('improvement_pct', 0)}%"],
        ]
        story.extend(branded_table(stats_data, styles))
        story.append(Spacer(1, 12))

        # Best variant highlight
        best = domain.get("best_variant")
        if best:
            story.append(Paragraph("Best Performing Variant:", styles["Heading3"]))
            story.append(Spacer(1, 4))

            variant_style = ParagraphStyle(
                "VariantText",
                parent=styles["BodyText"],
                backColor=HexColor("#2a2a3e"),
                borderPadding=8,
                leftIndent=12,
                rightIndent=12,
                fontSize=9,
                leading=13,
            )
            story.append(Paragraph(f'"{best.get("text", "N/A")[:300]}"', variant_style))
            story.append(Spacer(1, 4))
            story.append(Paragraph(
                f'Score: <b>{best.get("score", 0):.4f}</b> | '
                f'Hypothesis: {best.get("hypothesis", "N/A")[:100]}',
                styles["BodyText"]
            ))
            story.append(Spacer(1, 12))

        # Recent learnings
        learnings = domain.get("recent_learnings", [])
        if learnings:
            story.append(Paragraph("Recent Learnings:", styles["Heading3"]))
            story.append(Spacer(1, 4))
            learning_items = []
            for l in learnings[:5]:
                emoji = "+" if l.get("result") == "kept" else "-"
                learning_items.append(
                    f"[{emoji}] {l.get('hypothesis', 'N/A')[:80]} — "
                    f"<i>{l.get('learnings', 'N/A')[:100]}</i>"
                )
            story.extend(bullet_list(learning_items, styles))
            story.append(Spacer(1, 12))

        # Active experiments
        active = domain.get("active_experiments", [])
        if active:
            story.append(Paragraph("Active Experiments:", styles["Heading3"]))
            story.append(Spacer(1, 4))
            active_data = [["ID", "Status", "Hypothesis"]]
            for exp in active[:5]:
                active_data.append([
                    exp.get("id", "")[:20],
                    exp.get("status", ""),
                    exp.get("hypothesis", "")[:50],
                ])
            story.extend(branded_table(active_data, styles))

        story.append(Spacer(1, 20))

    # Footer
    story.append(accent_line())
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "AutoIterator — Autonomous optimization powered by Claude. "
        "All experiments are logged and reversible.",
        styles["Footer"] if "Footer" in styles else styles["BodyText"]
    ))

    return story
