#!/usr/bin/env python3
"""
Video Analytics Dashboard

View detailed analytics and cost reports for video generation.
Tracks usage of MoviePy vs Creatomate to optimize costs.

Usage:
    python video_analytics_dashboard.py                    # Show 30-day stats
    python video_analytics_dashboard.py --days 7           # Show 7-day stats
    python video_analytics_dashboard.py --days 90          # Show 90-day stats
    python video_analytics_dashboard.py --export report.json  # Export to JSON
"""

import sys
import json
import argparse
from pathlib import Path
from typing import Dict, Any

# Import the router for analytics
from intelligent_video_router import IntelligentVideoRouter


def print_ascii_chart(label: str, value: float, max_value: float, width: int = 40):
    """
    Print ASCII bar chart.
    
    Args:
        label: Label for the bar
        value: Value to display
        max_value: Maximum value for scaling
        width: Width of the bar in characters
    """
    if max_value == 0:
        bar_width = 0
    else:
        bar_width = int((value / max_value) * width)
    
    bar = '█' * bar_width
    print(f"  {label:20s} {bar} {value:.0f}")


def print_detailed_report(stats: Dict[str, Any]):
    """
    Print comprehensive analytics report with visualizations.
    
    Args:
        stats: Statistics dict from IntelligentVideoRouter
    """
    if stats.get('total_videos', 0) == 0:
        print("\n" + "="*70)
        print("NO DATA AVAILABLE")
        print("="*70)
        print("\nNo video generation data found.")
        print("Create some videos first, then check back here for analytics!")
        return
    
    print("\n" + "="*70)
    print(f"VIDEO GENERATION ANALYTICS DASHBOARD")
    print(f"Period: Last {stats['period_days']} Days")
    print("="*70)
    
    # Executive Summary
    print("\n" + "="*70)
    print("EXECUTIVE SUMMARY")
    print("="*70)
    
    print(f"\n📊 Total Videos Generated: {stats['total_successful']}")
    print(f"💰 Total Cost: ${stats['total_cost']:.2f}")
    print(f"📈 Average Cost per Video: ${stats['average_cost_per_video']:.3f}")
    
    # Cost savings calculation
    potential_cost = stats['total_successful'] * 0.05  # All Creatomate
    savings = potential_cost - stats['total_cost']
    savings_pct = (savings / potential_cost * 100) if potential_cost > 0 else 0
    
    print(f"💎 Cost Savings: ${savings:.2f} ({savings_pct:.1f}% saved)")
    
    # Method Breakdown with Visual Charts
    print("\n" + "="*70)
    print("METHOD BREAKDOWN")
    print("="*70)
    
    mp = stats['moviepy']
    cm = stats['creatomate']
    
    max_videos = max(mp['successful'], cm['successful'])
    
    print("\n📦 Videos Generated by Method:")
    print_ascii_chart("MoviePy (Free)", mp['successful'], max_videos)
    print_ascii_chart("Creatomate ($0.05)", cm['successful'], max_videos)
    
    print(f"\n🎯 Success Rates:")
    print(f"  MoviePy:    {mp['success_rate']:.1f}% ({mp['successful']}/{mp['total_attempts']} attempts)")
    print(f"  Creatomate: {cm['success_rate']:.1f}% ({cm['successful']}/{cm['total_attempts']} attempts)")
    
    print(f"\n💵 Cost Breakdown:")
    print(f"  MoviePy:    ${mp['total_cost']:.2f} (free local processing)")
    print(f"  Creatomate: ${cm['total_cost']:.2f} ({cm['successful']} videos × $0.05)")
    
    # Distribution pie chart (ASCII)
    print(f"\n📊 Distribution:")
    moviepy_pct = mp['percentage_of_total']
    creatomate_pct = cm['percentage_of_total']
    
    moviepy_blocks = int(moviepy_pct / 2)  # 50 blocks = 100%
    creatomate_blocks = int(creatomate_pct / 2)
    
    print(f"  [{'█' * moviepy_blocks}{'░' * creatomate_blocks}]")
    print(f"   {moviepy_pct:.1f}% MoviePy (free)      {creatomate_pct:.1f}% Creatomate (paid)")
    
    # Cost Analysis & Projections
    print("\n" + "="*70)
    print("COST ANALYSIS & PROJECTIONS")
    print("="*70)
    
    ca = stats['cost_analysis']
    
    print(f"\nProjected cost at 200 videos/month:")
    print(f"  Your hybrid system: ${ca['projected_monthly_cost_200_videos']:.2f}/month")
    print(f"  Creatomate-only:    ${ca['creatomate_only_cost_200_videos']:.2f}/month")
    print(f"  ────────────────────────────────")
    print(f"  Monthly savings:    ${ca['monthly_savings']:.2f}")
    print(f"  Yearly savings:     ${ca['yearly_savings']:.2f}")
    
    # ROI Visualization
    if ca['monthly_savings'] > 0:
        roi_pct = (ca['monthly_savings'] / ca['creatomate_only_cost_200_videos'] * 100)
        print(f"\n💰 ROI: {roi_pct:.1f}% cost reduction vs Creatomate-only")
    
    # Performance Insights
    print("\n" + "="*70)
    print("PERFORMANCE INSIGHTS")
    print("="*70)
    
    insights = []
    
    # MoviePy performance
    if mp['success_rate'] >= 80:
        insights.append("✅ MoviePy performing excellently! Keep it up.")
    elif mp['success_rate'] >= 70:
        insights.append("✓ MoviePy performing well. Good cost optimization.")
    elif mp['success_rate'] >= 50:
        insights.append("⚠️  MoviePy success rate could be improved. Check common failures.")
    else:
        insights.append("❌ MoviePy success rate is low. Investigate issues.")
    
    # Distribution
    if moviepy_pct >= 70:
        insights.append(f"✅ Excellent! {moviepy_pct:.0f}% of videos using free MoviePy.")
    elif moviepy_pct >= 60:
        insights.append(f"✓ Good balance. {moviepy_pct:.0f}% of videos using free MoviePy.")
    else:
        insights.append(f"⚠️  Only {moviepy_pct:.0f}% videos using free MoviePy. Room for improvement.")
    
    # Cost efficiency
    if stats['average_cost_per_video'] <= 0.02:
        insights.append(f"✅ Excellent cost efficiency: ${stats['average_cost_per_video']:.3f} per video!")
    elif stats['average_cost_per_video'] <= 0.03:
        insights.append(f"✓ Good cost efficiency: ${stats['average_cost_per_video']:.3f} per video")
    else:
        insights.append(f"⚠️  Average cost higher than target: ${stats['average_cost_per_video']:.3f} per video")
    
    # Volume
    if stats['total_successful'] >= 100:
        insights.append(f"🚀 High volume: {stats['total_successful']} videos generated!")
    elif stats['total_successful'] >= 50:
        insights.append(f"📈 Good volume: {stats['total_successful']} videos generated")
    else:
        insights.append(f"📊 Building momentum: {stats['total_successful']} videos so far")
    
    for insight in insights:
        print(f"\n  {insight}")
    
    # Recommendations
    print("\n" + "="*70)
    print("RECOMMENDATIONS")
    print("="*70)
    
    recommendations = []
    
    if mp['success_rate'] < 70 and mp['total_attempts'] > 10:
        recommendations.append(
            "• Investigate MoviePy failures to improve success rate\n"
            "  Run: grep -i error .tmp/logs/video_generation.jsonl | tail -20"
        )
    
    if moviepy_pct < 60 and stats['total_successful'] > 20:
        recommendations.append(
            "• More videos could use free MoviePy. Check complexity analysis.\n"
            "  Most fitness ads are 'simple' and should work with MoviePy."
        )
    
    if cm['failed'] > 5:
        recommendations.append(
            f"• {cm['failed']} Creatomate failures detected. Check API key and rate limits."
        )
    
    if stats['total_successful'] < 10:
        recommendations.append(
            "• Generate more videos to get statistically significant analytics.\n"
            "  Try creating at least 20-30 videos for meaningful insights."
        )
    
    if ca['monthly_savings'] > 5 and stats['total_successful'] >= 20:
        recommendations.append(
            f"• Great job! You're saving ${ca['yearly_savings']:.2f}/year with the hybrid approach.\n"
            "  This is working as designed - keep using it!"
        )
    
    if recommendations:
        for rec in recommendations:
            print(f"\n{rec}")
    else:
        print("\n✅ System running optimally! No recommendations at this time.")
    
    print()


def export_stats_json(stats: Dict[str, Any], output_path: str):
    """
    Export statistics to JSON file.
    
    Args:
        stats: Statistics dict
        output_path: Path to output JSON file
    """
    with open(output_path, 'w') as f:
        json.dump(stats, f, indent=2)
    
    print(f"\n✓ Statistics exported to: {output_path}")


def main():
    """CLI for video analytics dashboard."""
    parser = argparse.ArgumentParser(
        description="Video generation analytics dashboard"
    )
    
    parser.add_argument(
        '--days',
        type=int,
        default=30,
        help='Number of days to analyze (default: 30)'
    )
    
    parser.add_argument(
        '--export',
        help='Export statistics to JSON file'
    )
    
    parser.add_argument(
        '--simple',
        action='store_true',
        help='Show simple summary only (no detailed charts)'
    )
    
    args = parser.parse_args()
    
    # Create router to access statistics
    router = IntelligentVideoRouter()
    
    # Get statistics
    stats = router.get_statistics(days=args.days)
    
    # Print report
    if args.simple:
        router.print_statistics(days=args.days)
    else:
        print_detailed_report(stats)
    
    # Export if requested
    if args.export:
        export_stats_json(stats, args.export)


if __name__ == "__main__":
    main()