"""ClaimBack PDF Packager — Assembles professional dispute packages.

Uses the branded PDF engine to create court-ready dispute packages with
all evidence, letters, timelines, and legal citations in a single PDF.
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Add execution dir for branded_pdf_engine
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent / "execution"))

try:
    from branded_pdf_engine import BrandedPDF
except ImportError:
    BrandedPDF = None


def generate_dispute_package(dispute: dict, letters: list, analysis: dict,
                              output_path: str) -> str:
    """Generate a complete dispute package PDF.

    Args:
        dispute: Dispute record dict.
        letters: List of generated letter dicts.
        analysis: AI analysis dict.
        output_path: Where to save the PDF.

    Returns:
        Path to the generated PDF.
    """
    if BrandedPDF is None:
        return _generate_simple_package(dispute, letters, analysis, output_path)

    pdf = BrandedPDF(
        title=f"Dispute Package — {dispute.get('title', 'Medical Billing Dispute')}",
        subtitle="ClaimBack™ Medical Billing Dispute Platform",
        output_path=output_path,
    )

    # Cover page info
    pdf.add_section("Dispute Summary")
    summary_data = [
        ("Dispute Type", dispute.get("dispute_type", "").replace("_", " ").title()),
        ("Provider", dispute.get("provider_name", "N/A")),
        ("Insurance", dispute.get("insurance_company", "N/A")),
        ("Claim Number", dispute.get("claim_number", "N/A")),
        ("Date of Service", dispute.get("date_of_service", "N/A")),
        ("Total Billed", f"${float(dispute.get('billed_amount') or 0):,.2f}"),
        ("Insurance Paid", f"${float(dispute.get('insurance_paid') or 0):,.2f}"),
        ("Patient Responsibility", f"${float(dispute.get('patient_responsibility') or 0):,.2f}"),
        ("State", dispute.get("state", "N/A")),
        ("Deadline", dispute.get("deadline_date", "N/A")),
    ]
    for label, value in summary_data:
        pdf.add_body_text(f"**{label}:** {value}")

    # Patient description
    if dispute.get("description"):
        pdf.add_section("Patient Statement")
        pdf.add_body_text(dispute["description"])

    # AI Analysis
    if analysis:
        pdf.add_section("AI Case Analysis")

        if analysis.get("summary"):
            pdf.add_body_text(analysis["summary"])

        if analysis.get("strength_score") is not None:
            pdf.add_body_text(f"\n**Case Strength Score: {analysis['strength_score']}/10**")

        if analysis.get("errors_found"):
            pdf.add_subsection("Billing Errors Identified")
            for error in analysis["errors_found"]:
                pdf.add_body_text(f"• {error}")

        if analysis.get("applicable_laws"):
            pdf.add_subsection("Applicable Laws & Regulations")
            for law in analysis["applicable_laws"]:
                pdf.add_body_text(f"• {law}")

        if analysis.get("recommended_actions"):
            pdf.add_subsection("Recommended Actions")
            for i, action in enumerate(analysis["recommended_actions"], 1):
                pdf.add_body_text(f"{i}. {action}")

        if analysis.get("billing_code_analysis"):
            pdf.add_subsection("Billing Code Analysis")
            pdf.add_body_text(analysis["billing_code_analysis"])

        if analysis.get("system_tactics_identified"):
            pdf.add_subsection("System Tactics Identified")
            if isinstance(analysis["system_tactics_identified"], list):
                for tactic in analysis["system_tactics_identified"]:
                    pdf.add_body_text(f"• {tactic}")
            else:
                pdf.add_body_text(str(analysis["system_tactics_identified"]))

        if analysis.get("nuclear_options"):
            pdf.add_subsection("Escalation Options")
            if isinstance(analysis["nuclear_options"], list):
                for option in analysis["nuclear_options"]:
                    pdf.add_body_text(f"• {option}")
            else:
                pdf.add_body_text(str(analysis["nuclear_options"]))

    # Generated Letters
    if letters:
        pdf.add_section("Generated Letters")
        for letter in letters:
            letter_type = letter.get("letter_type", "Letter").replace("_", " ").title()
            pdf.add_subsection(letter_type)
            pdf.add_body_text(letter.get("content", ""))

    # Footer
    pdf.add_section("Disclaimer")
    pdf.add_body_text(
        "This dispute package was generated by ClaimBack™, a product of Marceau Solutions™. "
        "This document is not legal advice. For complex legal matters, consult an attorney. "
        f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    )

    pdf.build()
    return output_path


def _generate_simple_package(dispute: dict, letters: list, analysis: dict,
                              output_path: str) -> str:
    """Fallback plain-text package if branded PDF engine isn't available."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    doc = SimpleDocTemplate(output_path, pagesize=letter,
                            leftMargin=inch, rightMargin=inch,
                            topMargin=inch, bottomMargin=inch)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"<b>Dispute Package — {dispute.get('title', 'Dispute')}</b>",
                           styles["Title"]))
    story.append(Spacer(1, 12))

    details = [
        f"Provider: {dispute.get('provider_name', 'N/A')}",
        f"Insurance: {dispute.get('insurance_company', 'N/A')}",
        f"Billed: ${float(dispute.get('billed_amount') or 0):,.2f}",
        f"Date of Service: {dispute.get('date_of_service', 'N/A')}",
    ]
    for d in details:
        story.append(Paragraph(d, styles["Normal"]))
    story.append(Spacer(1, 12))

    if analysis and analysis.get("summary"):
        story.append(Paragraph("<b>Analysis</b>", styles["Heading2"]))
        story.append(Paragraph(analysis["summary"], styles["Normal"]))
        story.append(Spacer(1, 12))

    for lt in letters:
        story.append(Paragraph(
            f"<b>{lt.get('letter_type', 'Letter').replace('_', ' ').title()}</b>",
            styles["Heading2"]
        ))
        # Split content into paragraphs to handle long text
        for para in (lt.get("content", "")).split("\n\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), styles["Normal"]))
                story.append(Spacer(1, 6))
        story.append(Spacer(1, 12))

    doc.build(story)
    return output_path
