#!/bin/bash
#
# EC2 Instance Hardening Script
# =============================
#
# Implements security best practices for Ubuntu EC2 instances.
# Run as root or with sudo.
#
# Usage:
#   sudo ./ec2-hardening.sh
#
# What this script does:
# 1. System updates and automatic security patches
# 2. SSH hardening (key-only auth, no root login)
# 3. Firewall configuration (ufw)
# 4. fail2ban for brute-force protection
# 5. auditd for system monitoring
# 6. Secure system settings (sysctl)
# 7. Remove unnecessary packages
#
# Created: 2026-01-29
# Version: 1.0.0

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (use sudo)"
fi

log "Starting EC2 hardening..."

# ─────────────────────────────────────────────────────────────
# 1. System Updates
# ─────────────────────────────────────────────────────────────
log "Step 1: Installing updates..."

apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

# Install essential security packages
apt-get install -y -qq \
    unattended-upgrades \
    fail2ban \
    ufw \
    auditd \
    audispd-plugins \
    aide \
    rkhunter \
    logwatch \
    htop \
    net-tools

# Configure automatic security updates
log "Configuring automatic security updates..."
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# ─────────────────────────────────────────────────────────────
# 2. SSH Hardening
# ─────────────────────────────────────────────────────────────
log "Step 2: Hardening SSH..."

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.$(date +%Y%m%d)

# Apply secure SSH settings
cat > /etc/ssh/sshd_config.d/hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by ec2-hardening.sh

# Disable root login
PermitRootLogin no

# Key-based authentication only
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey

# Disable empty passwords
PermitEmptyPasswords no

# Disable X11 forwarding
X11Forwarding no

# Set login grace time
LoginGraceTime 60

# Maximum authentication attempts
MaxAuthTries 3

# Maximum sessions
MaxSessions 3

# Client alive settings (disconnect idle sessions)
ClientAliveInterval 300
ClientAliveCountMax 2

# Use strong ciphers only
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Use strong MACs only
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# Use strong key exchange
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# Logging
LogLevel VERBOSE

# Disable SSH tunneling unless needed
AllowTcpForwarding no
AllowStreamLocalForwarding no
GatewayPorts no
PermitTunnel no

# Banner (optional)
Banner /etc/ssh/banner.txt
EOF

# Create SSH banner
cat > /etc/ssh/banner.txt << 'EOF'
***************************************************************************
                       AUTHORIZED ACCESS ONLY
***************************************************************************
This system is the property of Marceau Solutions.
Unauthorized access is prohibited and will be prosecuted.
All activities are logged and monitored.
***************************************************************************
EOF

# Restart SSH (be careful - make sure you have console access!)
log "Restarting SSH service..."
systemctl restart sshd

# ─────────────────────────────────────────────────────────────
# 3. Firewall Configuration
# ─────────────────────────────────────────────────────────────
log "Step 3: Configuring firewall (UFW)..."

# Reset UFW
ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (essential!)
ufw allow 22/tcp comment 'SSH'

# Allow HTTP/HTTPS if needed (comment out if not a web server)
# ufw allow 80/tcp comment 'HTTP'
# ufw allow 443/tcp comment 'HTTPS'

# Enable UFW
ufw --force enable
ufw status verbose

warn "UFW is now active. If you need to open additional ports, use:"
warn "  sudo ufw allow <port>/tcp comment 'Description'"

# ─────────────────────────────────────────────────────────────
# 4. fail2ban Configuration
# ─────────────────────────────────────────────────────────────
log "Step 4: Configuring fail2ban..."

cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 3
destemail = root@localhost
sender = fail2ban@localhost
action = %(action_mwl)s

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 24h

[sshd-ddos]
enabled = true
port = ssh
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 6
findtime = 10m
bantime = 48h
EOF

systemctl enable fail2ban
systemctl restart fail2ban

log "fail2ban status:"
fail2ban-client status

# ─────────────────────────────────────────────────────────────
# 5. Audit Logging
# ─────────────────────────────────────────────────────────────
log "Step 5: Configuring audit logging..."

cat > /etc/audit/rules.d/hardening.rules << 'EOF'
# Remove any existing rules
-D

# Buffer Size
-b 8192

# Failure Mode (1 = printk, 2 = panic)
-f 1

# Identity changes
-w /etc/passwd -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/sudoers -p wa -k identity

# Network configuration
-w /etc/hosts -p wa -k network
-w /etc/network/ -p wa -k network

# SSH configuration
-w /etc/ssh/sshd_config -p wa -k sshd
-w /etc/ssh/sshd_config.d/ -p wa -k sshd

# Login monitoring
-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins

# Process monitoring
-a always,exit -F arch=b64 -S execve -k exec

# Module loading
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules

# Time changes
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change

# Privileged commands
-a always,exit -F path=/usr/bin/sudo -F perm=x -k privileged

# Make config immutable (until reboot)
-e 2
EOF

systemctl enable auditd
systemctl restart auditd

# ─────────────────────────────────────────────────────────────
# 6. Secure System Settings
# ─────────────────────────────────────────────────────────────
log "Step 6: Applying secure sysctl settings..."

cat > /etc/sysctl.d/99-security.conf << 'EOF'
# IP Spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Block SYN attacks
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log Martians
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore Directed pings
net.ipv4.icmp_echo_ignore_all = 0

# Disable IPv6 if not needed (uncomment if desired)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# Kernel hardening
kernel.randomize_va_space = 2
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
EOF

sysctl -p /etc/sysctl.d/99-security.conf

# ─────────────────────────────────────────────────────────────
# 7. File Permissions
# ─────────────────────────────────────────────────────────────
log "Step 7: Securing file permissions..."

# Secure cron
chmod 700 /etc/crontab
chmod 700 /etc/cron.d
chmod 700 /etc/cron.daily
chmod 700 /etc/cron.hourly
chmod 700 /etc/cron.weekly
chmod 700 /etc/cron.monthly

# Secure SSH
chmod 600 /etc/ssh/sshd_config
chmod 700 /etc/ssh/sshd_config.d

# Secure passwd/shadow
chmod 644 /etc/passwd
chmod 400 /etc/shadow
chmod 644 /etc/group
chmod 400 /etc/gshadow

# ─────────────────────────────────────────────────────────────
# 8. Remove Unnecessary Services
# ─────────────────────────────────────────────────────────────
log "Step 8: Disabling unnecessary services..."

# List of services to disable (uncomment as needed)
SERVICES_TO_DISABLE=(
    # "cups"          # Printing
    # "avahi-daemon"  # mDNS
    # "bluetooth"     # Bluetooth
)

for service in "${SERVICES_TO_DISABLE[@]}"; do
    if systemctl is-active --quiet "$service" 2>/dev/null; then
        log "Disabling $service..."
        systemctl stop "$service"
        systemctl disable "$service"
    fi
done

# ─────────────────────────────────────────────────────────────
# 9. Create Security Summary
# ─────────────────────────────────────────────────────────────
log "Creating security summary..."

SUMMARY_FILE="/root/security-hardening-summary.txt"
cat > "$SUMMARY_FILE" << EOF
EC2 Security Hardening Summary
==============================
Date: $(date)
Hostname: $(hostname)
Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null || echo "N/A")

Applied Configurations:
- Automatic security updates: ENABLED
- SSH key-only authentication: ENABLED
- SSH root login: DISABLED
- fail2ban: ENABLED (24h ban after 3 failed attempts)
- UFW firewall: ENABLED (only SSH allowed by default)
- Audit logging: ENABLED
- Sysctl hardening: APPLIED

SSH Configuration:
- Port: 22
- Authentication: Public key only
- Max attempts: 3
- Idle timeout: 10 minutes

Firewall Rules:
$(ufw status numbered)

fail2ban Status:
$(fail2ban-client status 2>/dev/null || echo "Not available")

Next Steps:
1. Review and test all services
2. Open additional firewall ports as needed: sudo ufw allow <port>/tcp
3. Configure CloudWatch agent for monitoring
4. Set up SNS alerts for security events
5. Enable AWS GuardDuty
6. Schedule regular security audits

Files Modified:
- /etc/ssh/sshd_config.d/hardening.conf
- /etc/apt/apt.conf.d/50unattended-upgrades
- /etc/fail2ban/jail.local
- /etc/audit/rules.d/hardening.rules
- /etc/sysctl.d/99-security.conf

IMPORTANT: Test SSH access from a new terminal before closing this session!

EOF

log "Hardening complete! Summary saved to: $SUMMARY_FILE"
cat "$SUMMARY_FILE"

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   EC2 HARDENING COMPLETE${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}CRITICAL: Test SSH access from a new terminal before closing this session!${NC}"
echo ""
echo "To verify:"
echo "  ssh -i ~/.ssh/your-key.pem ubuntu@$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "YOUR_IP")"
echo ""
