"""
API Access Manager — Platform Knowledge Base
Comprehensive application guides, nuances, and best practices for each platform.
"""

# Recommended application order (easiest/fastest approval → hardest/longest)
APPLICATION_ORDER = [
    {
        "order": 1,
        "slug": "google-youtube",
        "name": "Google / YouTube",
        "reason": "Fastest approval. Most APIs are instant-access via Google Cloud Console. YouTube Data API v3 is free tier generous. Foundation for many other integrations.",
        "typical_timeline": "Instant to 1 day",
        "difficulty": "Easy",
    },
    {
        "order": 2,
        "slug": "reddit",
        "name": "Reddit",
        "reason": "Simple OAuth app registration. Script-type apps approved instantly. Higher-tier access requires brief review.",
        "typical_timeline": "Instant (script) / 1-3 days (web app)",
        "difficulty": "Easy",
    },
    {
        "order": 3,
        "slug": "x-twitter",
        "name": "X (Twitter)",
        "reason": "Free tier available instantly. Elevated/Pro access requires use-case review but turnaround is reasonable.",
        "typical_timeline": "Instant (Free) / 1-7 days (Basic/Pro)",
        "difficulty": "Medium",
    },
    {
        "order": 4,
        "slug": "pinterest",
        "name": "Pinterest",
        "reason": "Business account required but straightforward. API access via app creation is fairly quick.",
        "typical_timeline": "1-5 days",
        "difficulty": "Medium",
    },
    {
        "order": 5,
        "slug": "tiktok",
        "name": "TikTok",
        "reason": "Developer portal registration straightforward but app review can take time. Content posting API requires additional approval.",
        "typical_timeline": "3-14 days",
        "difficulty": "Medium-Hard",
    },
    {
        "order": 6,
        "slug": "meta",
        "name": "Meta (Facebook / Instagram)",
        "reason": "Most complex process. Requires business verification, app review for each permission, and ongoing compliance. Start early.",
        "typical_timeline": "1-6 weeks",
        "difficulty": "Hard",
    },
    {
        "order": 7,
        "slug": "linkedin",
        "name": "LinkedIn",
        "reason": "Very restrictive. Marketing API requires company page + LinkedIn approval. Most useful APIs gated behind partnerships.",
        "typical_timeline": "2-8 weeks",
        "difficulty": "Hard",
    },
    {
        "order": 8,
        "slug": "snapchat",
        "name": "Snapchat",
        "reason": "Limited public API access. Marketing API requires ad account. Kit APIs (Login Kit, Creative Kit) are more accessible.",
        "typical_timeline": "1-4 weeks",
        "difficulty": "Hard",
    },
]

# Detailed platform guides with step-by-step application processes
PLATFORM_GUIDES = {
    "google-youtube": {
        "name": "Google / YouTube",
        "icon": "fab fa-google",
        "color": "#4285F4",
        "api_portal": "https://console.cloud.google.com/apis",
        "docs_url": "https://developers.google.com/youtube/v3",
        "key_rotation_days": 90,
        "overview": """Google Cloud Platform provides access to YouTube Data API, YouTube Analytics, and many other Google services.
YouTube Data API v3 is the primary API for reading/writing YouTube data. Free tier: 10,000 units/day.""",
        "prerequisites": [
            "Google account (use wmarceau@marceausolutions.com)",
            "Google Cloud Platform project",
            "Billing account (free tier covers most use cases)",
        ],
        "best_practices": [
            "Create a dedicated GCP project per use case (e.g., 'marceau-youtube-creator')",
            "Enable only the APIs you need to minimize attack surface",
            "Use OAuth 2.0 for user data access, API keys for public data only",
            "Set up budget alerts to avoid unexpected charges",
            "Store credentials in .env, never in code",
            "Use service accounts for server-to-server communication",
        ],
        "key_types": [
            {"name": "API Key", "type": "api_key", "rotation_days": 90, "env_var": "GOOGLE_API_KEY"},
            {"name": "OAuth Client ID", "type": "secret", "rotation_days": 365, "env_var": "GOOGLE_CLIENT_ID"},
            {"name": "OAuth Client Secret", "type": "secret", "rotation_days": 365, "env_var": "GOOGLE_CLIENT_SECRET"},
            {"name": "Refresh Token", "type": "refresh_token", "rotation_days": 0, "env_var": "GOOGLE_REFRESH_TOKEN"},
        ],
        "steps": [
            (1, "Create Google Cloud Project", "Go to console.cloud.google.com → Create new project. Name it descriptively (e.g., 'marceau-youtube-creator'). Note the Project ID.", "manual"),
            (2, "Enable Billing", "Link a billing account to the project. Free tier covers YouTube Data API (10,000 units/day). Set budget alert at $5.", "manual"),
            (3, "Enable YouTube Data API v3", "APIs & Services → Library → Search 'YouTube Data API v3' → Enable. Also enable YouTube Analytics API if needed.", "manual"),
            (4, "Create OAuth Consent Screen", "APIs & Services → OAuth consent screen → External → Fill in app name, support email, authorized domains. Add scopes for YouTube.", "manual"),
            (5, "Create OAuth 2.0 Credentials", "APIs & Services → Credentials → Create Credentials → OAuth Client ID → Web application. Add authorized redirect URIs.", "manual"),
            (6, "Create API Key (optional)", "Credentials → Create Credentials → API Key. Restrict it to YouTube Data API and your IP/referrer.", "manual"),
            (7, "Store Credentials in .env", "Add GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_API_KEY to your .env file.", "automated"),
            (8, "Test API Access", "Run a test query against the YouTube Data API to verify credentials work.", "automated"),
            (9, "Submit for Verification (if needed)", "If accessing sensitive scopes, submit OAuth consent screen for Google verification. Can take 2-6 weeks.", "manual"),
        ],
        "nuances": [
            "YouTube API quota is measured in 'units' not requests — a search costs 100 units, a video upload costs 1600",
            "Unverified apps can only be used by test users you add manually (max 100)",
            "Refresh tokens can expire if unused for 6 months or if user revokes access",
            "API key restrictions (IP, referrer, API) are critical for security",
            "Service accounts cannot act as YouTube users — you need OAuth for channel operations",
        ],
    },
    "reddit": {
        "name": "Reddit",
        "icon": "fab fa-reddit",
        "color": "#FF4500",
        "api_portal": "https://www.reddit.com/prefs/apps",
        "docs_url": "https://www.reddit.com/dev/api/",
        "key_rotation_days": 0,  # Reddit tokens don't expire by default
        "overview": """Reddit API provides access to posts, comments, subreddits, and user data.
Three app types: script (personal use), web app (3rd party), installed app (mobile/desktop).
Rate limit: 100 requests/minute for OAuth, 10/minute for non-OAuth.""",
        "prerequisites": [
            "Reddit account with email verified",
            "Account should be at least 30 days old for higher rate limits",
        ],
        "best_practices": [
            "Use 'script' type for personal automation, 'web app' for products others will use",
            "Always use OAuth2 — basic auth is deprecated",
            "Set a descriptive User-Agent header (required, gets you blocked otherwise)",
            "Respect rate limits — Reddit will ban apps that abuse limits",
            "Use PRAW (Python Reddit API Wrapper) for easier integration",
        ],
        "key_types": [
            {"name": "Client ID", "type": "api_key", "rotation_days": 0, "env_var": "REDDIT_CLIENT_ID"},
            {"name": "Client Secret", "type": "secret", "rotation_days": 0, "env_var": "REDDIT_CLIENT_SECRET"},
            {"name": "Refresh Token", "type": "refresh_token", "rotation_days": 0, "env_var": "REDDIT_REFRESH_TOKEN"},
        ],
        "steps": [
            (1, "Log in to Reddit", "Go to reddit.com/prefs/apps using your Reddit account.", "manual"),
            (2, "Create Application", "Click 'create another app...' at the bottom. Choose 'script' for personal use or 'web app' for broader use.", "manual"),
            (3, "Fill Application Details", "Name: your app name. Redirect URI: http://localhost:8080 (for script type). Description: brief explanation of use.", "manual"),
            (4, "Note Credentials", "After creation, note the Client ID (under app name) and Client Secret.", "manual"),
            (5, "Generate Refresh Token (web app)", "If using web app type, implement OAuth flow to get refresh token. PRAW can help automate this.", "manual"),
            (6, "Store Credentials in .env", "Add REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET, REDDIT_REFRESH_TOKEN to .env.", "automated"),
            (7, "Test API Access", "Use PRAW or direct HTTP to verify: fetch your user profile or a subreddit listing.", "automated"),
            (8, "Request Higher Rate Limits (optional)", "Email api@reddit.com if you need >100 req/min. Include app description and expected usage.", "manual"),
        ],
        "nuances": [
            "Script apps are simplest — they authenticate as YOU, not as other users",
            "User-Agent MUST be unique and descriptive — Reddit blocks generic agents",
            "Reddit API is free but rate-limited. No paid tiers.",
            "Access tokens expire after 1 hour — always use refresh tokens",
            "Certain subreddits have additional API restrictions (quarantined, private)",
            "Reddit's API terms prohibit using data for ML training without permission",
        ],
    },
    "x-twitter": {
        "name": "X (Twitter)",
        "icon": "fab fa-x-twitter",
        "color": "#000000",
        "api_portal": "https://developer.x.com/en/portal/dashboard",
        "docs_url": "https://developer.x.com/en/docs",
        "key_rotation_days": 90,
        "overview": """X API v2 provides access to posts, users, spaces, and more.
Tiers: Free (limited write), Basic ($200/mo, 50k reads + 10k writes), Pro ($5000/mo).
Free tier: 1,500 posts/mo write, 500 reads, 1 app.""",
        "prerequisites": [
            "X account with verified phone number",
            "Developer account application at developer.x.com",
        ],
        "best_practices": [
            "Start with Free tier to validate your use case before upgrading",
            "Use OAuth 2.0 with PKCE for user context, App-only auth for public data",
            "Implement exponential backoff for rate limit handling",
            "Use the v2 API endpoints — v1.1 is being deprecated",
            "Keep your app's purpose description accurate — X reviews for compliance",
        ],
        "key_types": [
            {"name": "API Key", "type": "api_key", "rotation_days": 90, "env_var": "X_API_KEY"},
            {"name": "API Secret", "type": "secret", "rotation_days": 90, "env_var": "X_API_SECRET"},
            {"name": "Bearer Token", "type": "token", "rotation_days": 90, "env_var": "X_BEARER_TOKEN"},
            {"name": "Access Token", "type": "access_token", "rotation_days": 0, "env_var": "X_ACCESS_TOKEN"},
            {"name": "Access Token Secret", "type": "secret", "rotation_days": 0, "env_var": "X_ACCESS_TOKEN_SECRET"},
        ],
        "steps": [
            (1, "Sign Up for Developer Account", "Go to developer.x.com → Sign up. Use your X account credentials.", "manual"),
            (2, "Describe Your Use Case", "X requires a detailed description of how you'll use the API. Be specific about: what data you'll access, how you'll display it, whether you'll share data.", "manual"),
            (3, "Accept Developer Agreement", "Review and accept X Developer Agreement and Policy.", "manual"),
            (4, "Create a Project", "In the Developer Portal → Projects → Create Project. Choose the appropriate use case category.", "manual"),
            (5, "Create an App Within the Project", "Projects → Your Project → Add App. Name it descriptively.", "manual"),
            (6, "Generate Keys and Tokens", "App Settings → Keys and Tokens → Generate. Save API Key, API Secret, Bearer Token immediately — they're shown only once.", "manual"),
            (7, "Configure OAuth 2.0 (if needed)", "App Settings → User authentication settings → Set up. Configure callback URL, website URL, and permissions.", "manual"),
            (8, "Store All Credentials in .env", "Add all keys to .env: X_API_KEY, X_API_SECRET, X_BEARER_TOKEN, X_ACCESS_TOKEN, X_ACCESS_TOKEN_SECRET.", "automated"),
            (9, "Test API Access", "Make a test call to verify: GET /2/users/me with Bearer token.", "automated"),
            (10, "Apply for Elevated Access (optional)", "If you need more than Free tier limits, apply for Basic ($200/mo) or Pro ($5000/mo).", "manual"),
        ],
        "nuances": [
            "Keys are shown ONCE on generation — save them immediately",
            "Free tier is very limited: 1,500 posts/month write, 500 posts/month read",
            "X has aggressive automated use detection — avoid bulk operations",
            "App-only auth (Bearer token) can only read public data",
            "OAuth 1.0a is still required for some v1.1 endpoints",
            "X may suspend apps without warning if they detect policy violations",
            "Rate limits are per-user AND per-app — track both",
        ],
    },
    "meta": {
        "name": "Meta (Facebook / Instagram)",
        "icon": "fab fa-meta",
        "color": "#0668E1",
        "api_portal": "https://developers.facebook.com/apps/",
        "docs_url": "https://developers.facebook.com/docs/",
        "key_rotation_days": 60,
        "overview": """Meta's Graph API provides access to Facebook and Instagram data.
Requires business verification for production access. Each permission requires individual app review.
Instagram Basic Display API is being deprecated — use Instagram Graph API via Facebook.""",
        "prerequisites": [
            "Facebook account",
            "Facebook Business Manager account (business.facebook.com)",
            "Facebook Page connected to Instagram Professional account",
            "Business verification documents (EIN, utility bill, or domain verification)",
        ],
        "best_practices": [
            "Start with development mode — test everything before submitting for review",
            "Request ONLY the permissions you actually need — each adds review time",
            "Prepare screen recordings showing how each permission is used",
            "Business verification can take weeks — start this process immediately",
            "Use long-lived tokens (60 days) and implement automatic refresh",
            "Instagram Graph API requires a Facebook Page — set this up first",
        ],
        "key_types": [
            {"name": "App ID", "type": "api_key", "rotation_days": 0, "env_var": "META_APP_ID"},
            {"name": "App Secret", "type": "secret", "rotation_days": 180, "env_var": "META_APP_SECRET"},
            {"name": "User Access Token", "type": "access_token", "rotation_days": 60, "env_var": "META_USER_TOKEN"},
            {"name": "Page Access Token", "type": "access_token", "rotation_days": 0, "env_var": "META_PAGE_TOKEN"},
            {"name": "System User Token", "type": "access_token", "rotation_days": 0, "env_var": "META_SYSTEM_USER_TOKEN"},
        ],
        "steps": [
            (1, "Create Business Manager", "Go to business.facebook.com → Create Account. Use Marceau Solutions business details.", "manual"),
            (2, "Start Business Verification", "Business Settings → Business Info → Start Verification. Upload business documents. THIS CAN TAKE 1-4 WEEKS — do it first.", "manual"),
            (3, "Create Meta App", "developers.facebook.com → My Apps → Create App. Choose 'Business' type. Connect to your Business Manager.", "manual"),
            (4, "Add Products to App", "Add 'Facebook Login', 'Instagram Graph API', and any other products you need.", "manual"),
            (5, "Configure Facebook Login", "Settings → Valid OAuth Redirect URIs. Set up login flow for user token generation.", "manual"),
            (6, "Set Up Instagram Graph API", "Connect your Instagram Professional account to your Facebook Page. Add Instagram Graph API product to your app.", "manual"),
            (7, "Test in Development Mode", "Use Graph API Explorer to test all endpoints. Note: only works with test users and your own accounts.", "manual"),
            (8, "Prepare App Review Submission", "For each permission: write justification, create screen recording showing usage, prepare test credentials.", "manual"),
            (9, "Submit for App Review", "App Review → Permissions and Features → Request for each one. Include screen recordings and descriptions.", "manual"),
            (10, "Wait for Review + Respond", "Review takes 1-5 business days per permission. Respond promptly to any reviewer questions.", "manual"),
            (11, "Switch to Live Mode", "After approval: App Settings → App Mode → Live. Generate long-lived tokens.", "manual"),
            (12, "Generate Long-Lived Tokens", "Exchange short-lived token for long-lived (60 days). Set up automatic refresh.", "automated"),
            (13, "Store All Credentials in .env", "Add META_APP_ID, META_APP_SECRET, META_USER_TOKEN, META_PAGE_TOKEN to .env.", "automated"),
            (14, "Set Up Token Refresh Automation", "Create a scheduled job to refresh long-lived tokens before they expire (every 50 days).", "automated"),
        ],
        "nuances": [
            "Instagram API access REQUIRES a Facebook Page + Instagram Professional account linked",
            "Business verification is the #1 bottleneck — start before anything else",
            "Each permission requires separate review with screen recordings",
            "Short-lived tokens last 1 hour, long-lived tokens last 60 days — automate refresh",
            "Development mode limits you to app admins/testers only",
            "Instagram Basic Display API is deprecated — use Graph API through Facebook",
            "Rate limits: 200 calls/user/hour (Graph API), varies by endpoint",
            "Webhooks require HTTPS callback URL — no localhost",
            "Meta is the strictest platform — expect multiple review rounds",
            "Page tokens obtained from long-lived user tokens do NOT expire",
        ],
    },
    "tiktok": {
        "name": "TikTok",
        "icon": "fab fa-tiktok",
        "color": "#000000",
        "api_portal": "https://developers.tiktok.com/",
        "docs_url": "https://developers.tiktok.com/doc/overview/",
        "key_rotation_days": 365,
        "overview": """TikTok API provides access to user info, video publishing, and analytics.
Two main APIs: TikTok API for user data/publishing, TikTok Marketing API for ads.
Content posting requires additional review and approval.""",
        "prerequisites": [
            "TikTok account",
            "Business email for developer registration",
            "Clear use case description",
            "Privacy policy URL",
            "Terms of service URL",
        ],
        "best_practices": [
            "Start with Login Kit and Share Kit — they have the fastest approval",
            "Content Posting API requires additional approval — plan for extra time",
            "Use sandbox environment for all testing before going live",
            "TikTok requires re-authorization every 365 days",
            "Video specifications are strict — validate before upload",
        ],
        "key_types": [
            {"name": "Client Key", "type": "api_key", "rotation_days": 365, "env_var": "TIKTOK_CLIENT_KEY"},
            {"name": "Client Secret", "type": "secret", "rotation_days": 365, "env_var": "TIKTOK_CLIENT_SECRET"},
            {"name": "Access Token", "type": "access_token", "rotation_days": 1, "env_var": "TIKTOK_ACCESS_TOKEN"},
            {"name": "Refresh Token", "type": "refresh_token", "rotation_days": 365, "env_var": "TIKTOK_REFRESH_TOKEN"},
        ],
        "steps": [
            (1, "Register as TikTok Developer", "Go to developers.tiktok.com → Sign up with your TikTok account.", "manual"),
            (2, "Create an App", "Manage Apps → Create. Enter app name, icon, description.", "manual"),
            (3, "Configure App Details", "Set callback URL, privacy policy URL, terms of service URL. Choose the products/scopes you need.", "manual"),
            (4, "Select API Products", "Choose which APIs you need: Login Kit, Share Kit, Content Posting API, User Info, Video List, etc.", "manual"),
            (5, "Submit for Review", "Submit your app for TikTok review. Include detailed descriptions of each feature.", "manual"),
            (6, "Implement OAuth Flow (while waiting)", "Build the OAuth 2.0 authorization flow using TikTok's Login Kit.", "manual"),
            (7, "Test in Sandbox", "Use sandbox mode to test API calls with test accounts.", "manual"),
            (8, "Respond to Review Feedback", "TikTok may request changes or additional info. Respond within 7 days.", "manual"),
            (9, "Go Live After Approval", "Once approved, switch from sandbox to production.", "manual"),
            (10, "Store Credentials in .env", "Add TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET to .env.", "automated"),
            (11, "Set Up Token Refresh", "Access tokens expire daily. Implement automatic refresh using the refresh token.", "automated"),
        ],
        "nuances": [
            "Access tokens expire in 24 hours — refresh token flow is mandatory",
            "Refresh tokens expire in 365 days — set calendar reminder to re-authorize",
            "Content Posting API has additional approval requirements beyond basic access",
            "Video specs: MP4, max 287.6MB, 3s-60min, specific resolutions",
            "Sandbox mode uses test accounts — cannot access real user data",
            "TikTok's review process is less transparent than Meta's",
            "Rate limits vary by endpoint — check docs for each one",
            "Some markets (EU) have additional data privacy requirements",
        ],
    },
    "linkedin": {
        "name": "LinkedIn",
        "icon": "fab fa-linkedin",
        "color": "#0A66C2",
        "api_portal": "https://www.linkedin.com/developers/apps",
        "docs_url": "https://learn.microsoft.com/en-us/linkedin/",
        "key_rotation_days": 365,
        "overview": """LinkedIn APIs are among the most restrictive. Consumer APIs are limited.
Marketing APIs require approved Company Page + Marketing Developer Platform access.
Most useful for: posting articles, company page management, ad campaigns.""",
        "prerequisites": [
            "LinkedIn account",
            "LinkedIn Company Page (for Marketing APIs)",
            "Company Page admin access",
            "Clear business justification",
        ],
        "best_practices": [
            "Start with Community Management API (most accessible) — Sign In with LinkedIn, share, profile",
            "Marketing Developer Platform requires application + is slow to approve",
            "Use OAuth 2.0 — LinkedIn only supports authorization code flow",
            "Test with the LinkedIn API Console before building",
            "Keep scope requests minimal — LinkedIn scrutinizes broad access",
        ],
        "key_types": [
            {"name": "Client ID", "type": "api_key", "rotation_days": 365, "env_var": "LINKEDIN_CLIENT_ID"},
            {"name": "Client Secret", "type": "secret", "rotation_days": 365, "env_var": "LINKEDIN_CLIENT_SECRET"},
            {"name": "Access Token", "type": "access_token", "rotation_days": 60, "env_var": "LINKEDIN_ACCESS_TOKEN"},
            {"name": "Refresh Token", "type": "refresh_token", "rotation_days": 365, "env_var": "LINKEDIN_REFRESH_TOKEN"},
        ],
        "steps": [
            (1, "Create LinkedIn App", "Go to linkedin.com/developers/apps → Create App. Associate with your Company Page.", "manual"),
            (2, "Verify Company Page Association", "Company Page admin must approve the app association. Check Company Page → Settings.", "manual"),
            (3, "Select API Products", "Products tab → Request Access to 'Sign In with LinkedIn using OpenID Connect', 'Share on LinkedIn', etc.", "manual"),
            (4, "Configure OAuth 2.0", "Auth tab → Add redirect URLs. Note Client ID and Client Secret.", "manual"),
            (5, "Request Marketing Developer Platform (optional)", "Products → Marketing Developer Platform → Request Access. Requires detailed business justification.", "manual"),
            (6, "Wait for Product Approval", "Some products auto-approve, others require LinkedIn review (1-4 weeks for Marketing).", "manual"),
            (7, "Generate Access Token", "Use OAuth flow or LinkedIn Token Generator tool for testing.", "manual"),
            (8, "Store Credentials in .env", "Add LINKEDIN_CLIENT_ID, LINKEDIN_CLIENT_SECRET, LINKEDIN_ACCESS_TOKEN to .env.", "automated"),
            (9, "Test API Access", "Test with GET /v2/userinfo or POST share to verify access.", "automated"),
            (10, "Set Up Token Refresh", "Access tokens expire in 60 days. Implement refresh flow.", "automated"),
        ],
        "nuances": [
            "LinkedIn is VERY restrictive — most APIs require product-level approval",
            "Marketing Developer Platform approval can take 2-8 weeks",
            "Access tokens expire in 60 days, refresh tokens in 365 days",
            "Company Page must be verified and have admin who approves app",
            "Rate limits: 100 requests/day for most endpoints (very low)",
            "r_liteprofile scope is deprecated — use OpenID Connect",
            "LinkedIn may revoke access if your app behavior changes from what was described",
            "Posting via API marks posts as 'via [App Name]' — cannot be hidden",
        ],
    },
    "pinterest": {
        "name": "Pinterest",
        "icon": "fab fa-pinterest",
        "color": "#E60023",
        "api_portal": "https://developers.pinterest.com/apps/",
        "docs_url": "https://developers.pinterest.com/docs/getting-started/",
        "key_rotation_days": 30,
        "overview": """Pinterest API v5 provides access to pins, boards, user data, and ads.
Business account required. API access is relatively straightforward.
Good for: pin creation, board management, analytics, ad campaigns.""",
        "prerequisites": [
            "Pinterest Business account",
            "App registered at developers.pinterest.com",
        ],
        "best_practices": [
            "Convert to business account if personal — it's free and instant",
            "Use sandbox mode for development and testing",
            "Pinterest access tokens are short-lived (30 days) — automate refresh",
            "Pin images should be 2:3 aspect ratio for best performance",
        ],
        "key_types": [
            {"name": "App ID", "type": "api_key", "rotation_days": 0, "env_var": "PINTEREST_APP_ID"},
            {"name": "App Secret", "type": "secret", "rotation_days": 365, "env_var": "PINTEREST_APP_SECRET"},
            {"name": "Access Token", "type": "access_token", "rotation_days": 30, "env_var": "PINTEREST_ACCESS_TOKEN"},
            {"name": "Refresh Token", "type": "refresh_token", "rotation_days": 365, "env_var": "PINTEREST_REFRESH_TOKEN"},
        ],
        "steps": [
            (1, "Create/Convert to Business Account", "Go to pinterest.com/business/create or convert existing personal account.", "manual"),
            (2, "Register as Developer", "Go to developers.pinterest.com → My Apps → Create App.", "manual"),
            (3, "Configure App", "Set redirect URI, app description, and website URL.", "manual"),
            (4, "Note App Credentials", "Copy App ID and App Secret from the app dashboard.", "manual"),
            (5, "Implement OAuth Flow", "Use authorization code flow to get access + refresh tokens.", "manual"),
            (6, "Test in Sandbox", "Use sandbox environment to test API calls.", "manual"),
            (7, "Submit for Production Access", "Request trial access or full access. Include use case description.", "manual"),
            (8, "Store Credentials in .env", "Add PINTEREST_APP_ID, PINTEREST_APP_SECRET, tokens to .env.", "automated"),
            (9, "Set Up Token Refresh", "Access tokens expire in 30 days. Automate refresh.", "automated"),
        ],
        "nuances": [
            "Access tokens expire in 30 days — shortest of all major platforms",
            "Business account is required — personal accounts cannot access API",
            "Sandbox mode has limited data — switch to production for real testing",
            "Pin creation rate limits: 10 pins/day in sandbox, varies in production",
            "Image requirements: JPEG or PNG, max 32MB, 2:3 ratio recommended",
            "Pinterest reviews apps for production access — takes 1-5 days typically",
        ],
    },
    "snapchat": {
        "name": "Snapchat",
        "icon": "fab fa-snapchat",
        "color": "#FFFC00",
        "api_portal": "https://kit.snapchat.com/manage/",
        "docs_url": "https://docs.snap.com/",
        "key_rotation_days": 365,
        "overview": """Snapchat offers Snap Kit (Login, Creative, Bitmoji) and Marketing API.
Snap Kit is more accessible for general development. Marketing API requires ad account.
Most useful for: AR lenses, creative tools, ad campaign management.""",
        "prerequisites": [
            "Snapchat account",
            "Developer portal registration",
            "For Marketing API: Snapchat Business account + ad account",
            "Privacy policy and terms of service URLs",
        ],
        "best_practices": [
            "Start with Login Kit — easiest to get approved",
            "Creative Kit for sharing content to Snapchat is also relatively easy",
            "Marketing API requires Snapchat ad account with spend history",
            "Snap Kit has strict branding guidelines — follow them exactly",
        ],
        "key_types": [
            {"name": "Client ID (OAuth)", "type": "api_key", "rotation_days": 365, "env_var": "SNAP_CLIENT_ID"},
            {"name": "Client Secret", "type": "secret", "rotation_days": 365, "env_var": "SNAP_CLIENT_SECRET"},
            {"name": "Organization ID", "type": "api_key", "rotation_days": 0, "env_var": "SNAP_ORG_ID"},
            {"name": "Marketing API Token", "type": "access_token", "rotation_days": 0, "env_var": "SNAP_MARKETING_TOKEN"},
        ],
        "steps": [
            (1, "Register on Snap Kit Portal", "Go to kit.snapchat.com → Sign in with Snapchat account → Create organization.", "manual"),
            (2, "Create an App", "Manage → Create New App. Add app name, description, and icons.", "manual"),
            (3, "Select Snap Kit Products", "Choose which Kits to enable: Login Kit, Creative Kit, Bitmoji Kit, etc.", "manual"),
            (4, "Configure OAuth Settings", "Set redirect URIs, add confidential client credentials.", "manual"),
            (5, "Submit for Review", "Each Kit requires separate approval. Include demo video and descriptions.", "manual"),
            (6, "Set Up Marketing API (optional)", "Go to business.snapchat.com → Create ad account → Request Marketing API access.", "manual"),
            (7, "Wait for Approval", "Snap Kit review: 1-2 weeks. Marketing API: 2-4 weeks.", "manual"),
            (8, "Store Credentials in .env", "Add SNAP_CLIENT_ID, SNAP_CLIENT_SECRET, SNAP_ORG_ID to .env.", "automated"),
            (9, "Test Integration", "Use Snap Kit SDK to verify login flow and creative sharing work.", "automated"),
        ],
        "nuances": [
            "Snap Kit and Marketing API are separate products with separate review processes",
            "Branding guidelines are strict — wrong Snapchat logo usage = rejection",
            "Login Kit provides limited user data compared to other platforms",
            "Creative Kit allows sharing but NOT reading Snapchat content",
            "Marketing API requires active ad spend — not available for non-advertisers",
            "Snap Kit review can be slow and opaque — follow up after 2 weeks",
            "AR/Lens Studio is a separate ecosystem with different access requirements",
        ],
    },
}


def get_platform_guide(slug):
    return PLATFORM_GUIDES.get(slug)


def get_all_platform_slugs():
    return list(PLATFORM_GUIDES.keys())


def get_application_order():
    return APPLICATION_ORDER
